### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by a-malinov** [mjhea0/Flask-Landing#1]
Traceback (most recent call last):
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 2000, in **call**
    return self.wsgi_app(environ, start_response)
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/landing/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/landing/lib/python2.7/site-packages/flask_debugtoolbar/**init**.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/root/landing/project/main/views.py", line 41, in index
    return render_template('main/index.html', form=form)
  File "/root/landing/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/root/landing/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/landing/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/root/landing/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/landing/project/templates/main/index.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "/root/landing/project/templates/_base.html", line 17, in top-level template code
    {% include "navigation.html" %}
  File "/root/landing/project/templates/navigation.html", line 17, in top-level template code
    {% if current_user.is_authenticated() %}
AttributeError: 'bool' object has no attribute '__call__'

**Comment by mjhea0** [comment]
the fix is in this thread -> https://github.com/lingthio/Flask-User-starter-app/issues/9. if you do fix it can you please submit a pr! 👍
